<div id="outdated-browser" class="invisible">
    <div class="logo text-center">
        <img src="<?= $block->getLogoSrc(); ?>"/>
    </div>
    <h3><?= __('You are using an outdated browser which our site does not support - Internet Explorer.'); ?></h3>
    <h4><?= __('Please change your browser to be able to use our website.'); ?></h4>
    <p>
        <a id="btnUpdateBrowser" href="http://outdatedbrowser.com/" target="_blank">
            <?= __('Change my browser now'); ?>
        </a>
    </p>
</div>
